apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: apache
    releaseName: apache
    valuesFile: values.yaml
    version: 9.6.3
    