apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app

helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: prometheus
    releaseName: prometheus
    valuesFile: values.yaml
    version: 22.7.0s