apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    releaseName: prometheus-stack
    valuesFile: values.yaml
    version: 45.27.2
