apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: apache
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fola2022/test-kustomization-helm.git
    path: apache/overlays/dev
    plugin:
      name: kustomize-enable-helm